# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Boksi/auxilo-box

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Boksi/auxilo-box

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Boksi/auxilo-box/CMakeFiles /home/pi/Boksi/auxilo-box/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Boksi/auxilo-box/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

#=============================================================================
# Target rules for targets named devices

# Build rule for target.
devices: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 devices
.PHONY : devices

# fast build rule for target.
devices/fast:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/build
.PHONY : devices/fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network
.PHONY : network

# fast build rule for target.
network/fast:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/build
.PHONY : network/fast

#=============================================================================
# Target rules for targets named nexa

# Build rule for target.
nexa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nexa
.PHONY : nexa

# fast build rule for target.
nexa/fast:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/build
.PHONY : nexa/fast

#=============================================================================
# Target rules for targets named nexa_pair

# Build rule for target.
nexa_pair: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nexa_pair
.PHONY : nexa_pair

# fast build rule for target.
nexa_pair/fast:
	$(MAKE) -f CMakeFiles/nexa_pair.dir/build.make CMakeFiles/nexa_pair.dir/build
.PHONY : nexa_pair/fast

#=============================================================================
# Target rules for targets named sensors

# Build rule for target.
sensors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sensors
.PHONY : sensors

# fast build rule for target.
sensors/fast:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/build
.PHONY : sensors/fast

#=============================================================================
# Target rules for targets named wlan

# Build rule for target.
wlan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wlan
.PHONY : wlan

# fast build rule for target.
wlan/fast:
	$(MAKE) -f CMakeFiles/wlan.dir/build.make CMakeFiles/wlan.dir/build
.PHONY : wlan/fast

Communications/Client.o: Communications/Client.cpp.o
.PHONY : Communications/Client.o

# target to build an object file
Communications/Client.cpp.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/Client.cpp.o
.PHONY : Communications/Client.cpp.o

Communications/Client.i: Communications/Client.cpp.i
.PHONY : Communications/Client.i

# target to preprocess a source file
Communications/Client.cpp.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/Client.cpp.i
.PHONY : Communications/Client.cpp.i

Communications/Client.s: Communications/Client.cpp.s
.PHONY : Communications/Client.s

# target to generate assembly for a file
Communications/Client.cpp.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/Client.cpp.s
.PHONY : Communications/Client.cpp.s

Communications/ClientObserver.o: Communications/ClientObserver.cpp.o
.PHONY : Communications/ClientObserver.o

# target to build an object file
Communications/ClientObserver.cpp.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/ClientObserver.cpp.o
.PHONY : Communications/ClientObserver.cpp.o

Communications/ClientObserver.i: Communications/ClientObserver.cpp.i
.PHONY : Communications/ClientObserver.i

# target to preprocess a source file
Communications/ClientObserver.cpp.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/ClientObserver.cpp.i
.PHONY : Communications/ClientObserver.cpp.i

Communications/ClientObserver.s: Communications/ClientObserver.cpp.s
.PHONY : Communications/ClientObserver.s

# target to generate assembly for a file
Communications/ClientObserver.cpp.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/ClientObserver.cpp.s
.PHONY : Communications/ClientObserver.cpp.s

Communications/ClientWrapper.o: Communications/ClientWrapper.cpp.o
.PHONY : Communications/ClientWrapper.o

# target to build an object file
Communications/ClientWrapper.cpp.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/ClientWrapper.cpp.o
.PHONY : Communications/ClientWrapper.cpp.o

Communications/ClientWrapper.i: Communications/ClientWrapper.cpp.i
.PHONY : Communications/ClientWrapper.i

# target to preprocess a source file
Communications/ClientWrapper.cpp.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/ClientWrapper.cpp.i
.PHONY : Communications/ClientWrapper.cpp.i

Communications/ClientWrapper.s: Communications/ClientWrapper.cpp.s
.PHONY : Communications/ClientWrapper.s

# target to generate assembly for a file
Communications/ClientWrapper.cpp.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/ClientWrapper.cpp.s
.PHONY : Communications/ClientWrapper.cpp.s

Communications/Message.o: Communications/Message.cpp.o
.PHONY : Communications/Message.o

# target to build an object file
Communications/Message.cpp.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/Message.cpp.o
.PHONY : Communications/Message.cpp.o

Communications/Message.i: Communications/Message.cpp.i
.PHONY : Communications/Message.i

# target to preprocess a source file
Communications/Message.cpp.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/Message.cpp.i
.PHONY : Communications/Message.cpp.i

Communications/Message.s: Communications/Message.cpp.s
.PHONY : Communications/Message.s

# target to generate assembly for a file
Communications/Message.cpp.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/Communications/Message.cpp.s
.PHONY : Communications/Message.cpp.s

Devices/NexaPlug/NexaPlug.o: Devices/NexaPlug/NexaPlug.cpp.o
.PHONY : Devices/NexaPlug/NexaPlug.o

# target to build an object file
Devices/NexaPlug/NexaPlug.cpp.o:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/NexaPlug.cpp.o
.PHONY : Devices/NexaPlug/NexaPlug.cpp.o

Devices/NexaPlug/NexaPlug.i: Devices/NexaPlug/NexaPlug.cpp.i
.PHONY : Devices/NexaPlug/NexaPlug.i

# target to preprocess a source file
Devices/NexaPlug/NexaPlug.cpp.i:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/NexaPlug.cpp.i
.PHONY : Devices/NexaPlug/NexaPlug.cpp.i

Devices/NexaPlug/NexaPlug.s: Devices/NexaPlug/NexaPlug.cpp.s
.PHONY : Devices/NexaPlug/NexaPlug.s

# target to generate assembly for a file
Devices/NexaPlug/NexaPlug.cpp.s:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/NexaPlug.cpp.s
.PHONY : Devices/NexaPlug/NexaPlug.cpp.s

Devices/NexaPlug/nexa.o: Devices/NexaPlug/nexa.c.o
.PHONY : Devices/NexaPlug/nexa.o

# target to build an object file
Devices/NexaPlug/nexa.c.o:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/nexa.c.o
.PHONY : Devices/NexaPlug/nexa.c.o

Devices/NexaPlug/nexa.i: Devices/NexaPlug/nexa.c.i
.PHONY : Devices/NexaPlug/nexa.i

# target to preprocess a source file
Devices/NexaPlug/nexa.c.i:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/nexa.c.i
.PHONY : Devices/NexaPlug/nexa.c.i

Devices/NexaPlug/nexa.s: Devices/NexaPlug/nexa.c.s
.PHONY : Devices/NexaPlug/nexa.s

# target to generate assembly for a file
Devices/NexaPlug/nexa.c.s:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/nexa.c.s
.PHONY : Devices/NexaPlug/nexa.c.s

Devices/NexaPlug/nexa.o: Devices/NexaPlug/nexa.h.o
.PHONY : Devices/NexaPlug/nexa.o

# target to build an object file
Devices/NexaPlug/nexa.h.o:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/nexa.h.o
.PHONY : Devices/NexaPlug/nexa.h.o

Devices/NexaPlug/nexa.i: Devices/NexaPlug/nexa.h.i
.PHONY : Devices/NexaPlug/nexa.i

# target to preprocess a source file
Devices/NexaPlug/nexa.h.i:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/nexa.h.i
.PHONY : Devices/NexaPlug/nexa.h.i

Devices/NexaPlug/nexa.s: Devices/NexaPlug/nexa.h.s
.PHONY : Devices/NexaPlug/nexa.s

# target to generate assembly for a file
Devices/NexaPlug/nexa.h.s:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/nexa.h.s
.PHONY : Devices/NexaPlug/nexa.h.s

Devices/NexaPlug/radio.o: Devices/NexaPlug/radio.c.o
.PHONY : Devices/NexaPlug/radio.o

# target to build an object file
Devices/NexaPlug/radio.c.o:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/radio.c.o
.PHONY : Devices/NexaPlug/radio.c.o

Devices/NexaPlug/radio.i: Devices/NexaPlug/radio.c.i
.PHONY : Devices/NexaPlug/radio.i

# target to preprocess a source file
Devices/NexaPlug/radio.c.i:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/radio.c.i
.PHONY : Devices/NexaPlug/radio.c.i

Devices/NexaPlug/radio.s: Devices/NexaPlug/radio.c.s
.PHONY : Devices/NexaPlug/radio.s

# target to generate assembly for a file
Devices/NexaPlug/radio.c.s:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/radio.c.s
.PHONY : Devices/NexaPlug/radio.c.s

Devices/NexaPlug/radio.o: Devices/NexaPlug/radio.h.o
.PHONY : Devices/NexaPlug/radio.o

# target to build an object file
Devices/NexaPlug/radio.h.o:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/radio.h.o
.PHONY : Devices/NexaPlug/radio.h.o

Devices/NexaPlug/radio.i: Devices/NexaPlug/radio.h.i
.PHONY : Devices/NexaPlug/radio.i

# target to preprocess a source file
Devices/NexaPlug/radio.h.i:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/radio.h.i
.PHONY : Devices/NexaPlug/radio.h.i

Devices/NexaPlug/radio.s: Devices/NexaPlug/radio.h.s
.PHONY : Devices/NexaPlug/radio.s

# target to generate assembly for a file
Devices/NexaPlug/radio.h.s:
	$(MAKE) -f CMakeFiles/nexa.dir/build.make CMakeFiles/nexa.dir/Devices/NexaPlug/radio.h.s
.PHONY : Devices/NexaPlug/radio.h.s

Devices/Plugs/Plugs.o: Devices/Plugs/Plugs.cpp.o
.PHONY : Devices/Plugs/Plugs.o

# target to build an object file
Devices/Plugs/Plugs.cpp.o:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/Devices/Plugs/Plugs.cpp.o
.PHONY : Devices/Plugs/Plugs.cpp.o

Devices/Plugs/Plugs.i: Devices/Plugs/Plugs.cpp.i
.PHONY : Devices/Plugs/Plugs.i

# target to preprocess a source file
Devices/Plugs/Plugs.cpp.i:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/Devices/Plugs/Plugs.cpp.i
.PHONY : Devices/Plugs/Plugs.cpp.i

Devices/Plugs/Plugs.s: Devices/Plugs/Plugs.cpp.s
.PHONY : Devices/Plugs/Plugs.s

# target to generate assembly for a file
Devices/Plugs/Plugs.cpp.s:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/Devices/Plugs/Plugs.cpp.s
.PHONY : Devices/Plugs/Plugs.cpp.s

Devices/Speaker/Speaker.o: Devices/Speaker/Speaker.cpp.o
.PHONY : Devices/Speaker/Speaker.o

# target to build an object file
Devices/Speaker/Speaker.cpp.o:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/Devices/Speaker/Speaker.cpp.o
.PHONY : Devices/Speaker/Speaker.cpp.o

Devices/Speaker/Speaker.i: Devices/Speaker/Speaker.cpp.i
.PHONY : Devices/Speaker/Speaker.i

# target to preprocess a source file
Devices/Speaker/Speaker.cpp.i:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/Devices/Speaker/Speaker.cpp.i
.PHONY : Devices/Speaker/Speaker.cpp.i

Devices/Speaker/Speaker.s: Devices/Speaker/Speaker.cpp.s
.PHONY : Devices/Speaker/Speaker.s

# target to generate assembly for a file
Devices/Speaker/Speaker.cpp.s:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/Devices/Speaker/Speaker.cpp.s
.PHONY : Devices/Speaker/Speaker.cpp.s

Devices/Voice/voice.o: Devices/Voice/voice.cpp.o
.PHONY : Devices/Voice/voice.o

# target to build an object file
Devices/Voice/voice.cpp.o:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/Devices/Voice/voice.cpp.o
.PHONY : Devices/Voice/voice.cpp.o

Devices/Voice/voice.i: Devices/Voice/voice.cpp.i
.PHONY : Devices/Voice/voice.i

# target to preprocess a source file
Devices/Voice/voice.cpp.i:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/Devices/Voice/voice.cpp.i
.PHONY : Devices/Voice/voice.cpp.i

Devices/Voice/voice.s: Devices/Voice/voice.cpp.s
.PHONY : Devices/Voice/voice.s

# target to generate assembly for a file
Devices/Voice/voice.cpp.s:
	$(MAKE) -f CMakeFiles/devices.dir/build.make CMakeFiles/devices.dir/Devices/Voice/voice.cpp.s
.PHONY : Devices/Voice/voice.cpp.s

Helpfunctions/helpfunctions.o: Helpfunctions/helpfunctions.cpp.o
.PHONY : Helpfunctions/helpfunctions.o

# target to build an object file
Helpfunctions/helpfunctions.cpp.o:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Helpfunctions/helpfunctions.cpp.o
.PHONY : Helpfunctions/helpfunctions.cpp.o

Helpfunctions/helpfunctions.i: Helpfunctions/helpfunctions.cpp.i
.PHONY : Helpfunctions/helpfunctions.i

# target to preprocess a source file
Helpfunctions/helpfunctions.cpp.i:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Helpfunctions/helpfunctions.cpp.i
.PHONY : Helpfunctions/helpfunctions.cpp.i

Helpfunctions/helpfunctions.s: Helpfunctions/helpfunctions.cpp.s
.PHONY : Helpfunctions/helpfunctions.s

# target to generate assembly for a file
Helpfunctions/helpfunctions.cpp.s:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Helpfunctions/helpfunctions.cpp.s
.PHONY : Helpfunctions/helpfunctions.cpp.s

Sensors/Humidity/Humidity.o: Sensors/Humidity/Humidity.cpp.o
.PHONY : Sensors/Humidity/Humidity.o

# target to build an object file
Sensors/Humidity/Humidity.cpp.o:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Sensors/Humidity/Humidity.cpp.o
.PHONY : Sensors/Humidity/Humidity.cpp.o

Sensors/Humidity/Humidity.i: Sensors/Humidity/Humidity.cpp.i
.PHONY : Sensors/Humidity/Humidity.i

# target to preprocess a source file
Sensors/Humidity/Humidity.cpp.i:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Sensors/Humidity/Humidity.cpp.i
.PHONY : Sensors/Humidity/Humidity.cpp.i

Sensors/Humidity/Humidity.s: Sensors/Humidity/Humidity.cpp.s
.PHONY : Sensors/Humidity/Humidity.s

# target to generate assembly for a file
Sensors/Humidity/Humidity.cpp.s:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Sensors/Humidity/Humidity.cpp.s
.PHONY : Sensors/Humidity/Humidity.cpp.s

Sensors/Switch/Switch.o: Sensors/Switch/Switch.cpp.o
.PHONY : Sensors/Switch/Switch.o

# target to build an object file
Sensors/Switch/Switch.cpp.o:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Sensors/Switch/Switch.cpp.o
.PHONY : Sensors/Switch/Switch.cpp.o

Sensors/Switch/Switch.i: Sensors/Switch/Switch.cpp.i
.PHONY : Sensors/Switch/Switch.i

# target to preprocess a source file
Sensors/Switch/Switch.cpp.i:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Sensors/Switch/Switch.cpp.i
.PHONY : Sensors/Switch/Switch.cpp.i

Sensors/Switch/Switch.s: Sensors/Switch/Switch.cpp.s
.PHONY : Sensors/Switch/Switch.s

# target to generate assembly for a file
Sensors/Switch/Switch.cpp.s:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Sensors/Switch/Switch.cpp.s
.PHONY : Sensors/Switch/Switch.cpp.s

Sensors/Thermometer/Thermometer.o: Sensors/Thermometer/Thermometer.cpp.o
.PHONY : Sensors/Thermometer/Thermometer.o

# target to build an object file
Sensors/Thermometer/Thermometer.cpp.o:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Sensors/Thermometer/Thermometer.cpp.o
.PHONY : Sensors/Thermometer/Thermometer.cpp.o

Sensors/Thermometer/Thermometer.i: Sensors/Thermometer/Thermometer.cpp.i
.PHONY : Sensors/Thermometer/Thermometer.i

# target to preprocess a source file
Sensors/Thermometer/Thermometer.cpp.i:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Sensors/Thermometer/Thermometer.cpp.i
.PHONY : Sensors/Thermometer/Thermometer.cpp.i

Sensors/Thermometer/Thermometer.s: Sensors/Thermometer/Thermometer.cpp.s
.PHONY : Sensors/Thermometer/Thermometer.s

# target to generate assembly for a file
Sensors/Thermometer/Thermometer.cpp.s:
	$(MAKE) -f CMakeFiles/sensors.dir/build.make CMakeFiles/sensors.dir/Sensors/Thermometer/Thermometer.cpp.s
.PHONY : Sensors/Thermometer/Thermometer.cpp.s

Wlan/wlan.o: Wlan/wlan.cpp.o
.PHONY : Wlan/wlan.o

# target to build an object file
Wlan/wlan.cpp.o:
	$(MAKE) -f CMakeFiles/wlan.dir/build.make CMakeFiles/wlan.dir/Wlan/wlan.cpp.o
.PHONY : Wlan/wlan.cpp.o

Wlan/wlan.i: Wlan/wlan.cpp.i
.PHONY : Wlan/wlan.i

# target to preprocess a source file
Wlan/wlan.cpp.i:
	$(MAKE) -f CMakeFiles/wlan.dir/build.make CMakeFiles/wlan.dir/Wlan/wlan.cpp.i
.PHONY : Wlan/wlan.cpp.i

Wlan/wlan.s: Wlan/wlan.cpp.s
.PHONY : Wlan/wlan.s

# target to generate assembly for a file
Wlan/wlan.cpp.s:
	$(MAKE) -f CMakeFiles/wlan.dir/build.make CMakeFiles/wlan.dir/Wlan/wlan.cpp.s
.PHONY : Wlan/wlan.cpp.s

demo.o: demo.cpp.o
.PHONY : demo.o

# target to build an object file
demo.cpp.o:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.o
.PHONY : demo.cpp.o

demo.i: demo.cpp.i
.PHONY : demo.i

# target to preprocess a source file
demo.cpp.i:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.i
.PHONY : demo.cpp.i

demo.s: demo.cpp.s
.PHONY : demo.s

# target to generate assembly for a file
demo.cpp.s:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.s
.PHONY : demo.cpp.s

nexa_pair.o: nexa_pair.cpp.o
.PHONY : nexa_pair.o

# target to build an object file
nexa_pair.cpp.o:
	$(MAKE) -f CMakeFiles/nexa_pair.dir/build.make CMakeFiles/nexa_pair.dir/nexa_pair.cpp.o
.PHONY : nexa_pair.cpp.o

nexa_pair.i: nexa_pair.cpp.i
.PHONY : nexa_pair.i

# target to preprocess a source file
nexa_pair.cpp.i:
	$(MAKE) -f CMakeFiles/nexa_pair.dir/build.make CMakeFiles/nexa_pair.dir/nexa_pair.cpp.i
.PHONY : nexa_pair.cpp.i

nexa_pair.s: nexa_pair.cpp.s
.PHONY : nexa_pair.s

# target to generate assembly for a file
nexa_pair.cpp.s:
	$(MAKE) -f CMakeFiles/nexa_pair.dir/build.make CMakeFiles/nexa_pair.dir/nexa_pair.cpp.s
.PHONY : nexa_pair.cpp.s

protocol.pb.o: protocol.pb.cc.o
.PHONY : protocol.pb.o

# target to build an object file
protocol.pb.cc.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/protocol.pb.cc.o
.PHONY : protocol.pb.cc.o

protocol.pb.i: protocol.pb.cc.i
.PHONY : protocol.pb.i

# target to preprocess a source file
protocol.pb.cc.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/protocol.pb.cc.i
.PHONY : protocol.pb.cc.i

protocol.pb.s: protocol.pb.cc.s
.PHONY : protocol.pb.s

# target to generate assembly for a file
protocol.pb.cc.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/protocol.pb.cc.s
.PHONY : protocol.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... demo"
	@echo "... devices"
	@echo "... edit_cache"
	@echo "... network"
	@echo "... nexa"
	@echo "... nexa_pair"
	@echo "... rebuild_cache"
	@echo "... sensors"
	@echo "... test"
	@echo "... wlan"
	@echo "... Communications/Client.o"
	@echo "... Communications/Client.i"
	@echo "... Communications/Client.s"
	@echo "... Communications/ClientObserver.o"
	@echo "... Communications/ClientObserver.i"
	@echo "... Communications/ClientObserver.s"
	@echo "... Communications/ClientWrapper.o"
	@echo "... Communications/ClientWrapper.i"
	@echo "... Communications/ClientWrapper.s"
	@echo "... Communications/Message.o"
	@echo "... Communications/Message.i"
	@echo "... Communications/Message.s"
	@echo "... Devices/NexaPlug/NexaPlug.o"
	@echo "... Devices/NexaPlug/NexaPlug.i"
	@echo "... Devices/NexaPlug/NexaPlug.s"
	@echo "... Devices/NexaPlug/nexa.o"
	@echo "... Devices/NexaPlug/nexa.i"
	@echo "... Devices/NexaPlug/nexa.s"
	@echo "... Devices/NexaPlug/nexa.o"
	@echo "... Devices/NexaPlug/nexa.i"
	@echo "... Devices/NexaPlug/nexa.s"
	@echo "... Devices/NexaPlug/radio.o"
	@echo "... Devices/NexaPlug/radio.i"
	@echo "... Devices/NexaPlug/radio.s"
	@echo "... Devices/NexaPlug/radio.o"
	@echo "... Devices/NexaPlug/radio.i"
	@echo "... Devices/NexaPlug/radio.s"
	@echo "... Devices/Plugs/Plugs.o"
	@echo "... Devices/Plugs/Plugs.i"
	@echo "... Devices/Plugs/Plugs.s"
	@echo "... Devices/Speaker/Speaker.o"
	@echo "... Devices/Speaker/Speaker.i"
	@echo "... Devices/Speaker/Speaker.s"
	@echo "... Devices/Voice/voice.o"
	@echo "... Devices/Voice/voice.i"
	@echo "... Devices/Voice/voice.s"
	@echo "... Helpfunctions/helpfunctions.o"
	@echo "... Helpfunctions/helpfunctions.i"
	@echo "... Helpfunctions/helpfunctions.s"
	@echo "... Sensors/Humidity/Humidity.o"
	@echo "... Sensors/Humidity/Humidity.i"
	@echo "... Sensors/Humidity/Humidity.s"
	@echo "... Sensors/Switch/Switch.o"
	@echo "... Sensors/Switch/Switch.i"
	@echo "... Sensors/Switch/Switch.s"
	@echo "... Sensors/Thermometer/Thermometer.o"
	@echo "... Sensors/Thermometer/Thermometer.i"
	@echo "... Sensors/Thermometer/Thermometer.s"
	@echo "... Wlan/wlan.o"
	@echo "... Wlan/wlan.i"
	@echo "... Wlan/wlan.s"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... nexa_pair.o"
	@echo "... nexa_pair.i"
	@echo "... nexa_pair.s"
	@echo "... protocol.pb.o"
	@echo "... protocol.pb.i"
	@echo "... protocol.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

